displayName: Rewrite Body with CSP (with compression support)

summary: A fork of Rewrite Body w/ compression support to post-process static pages and add nonces to them

type: middleware

import: github.com/joinrepublic/traefik-csp-middleware

testData:
  lastModified: true
  placeholder: DhcnhD3khTMePgXw
  monitor:
    types:
      - text/html
    methods: ["GET"]
